### ISSUE TITLE
Should we include carton in swiftwasm image?

### ISSUE THREAD

**Issue by kateinoigakukun** [swiftwasm/swiftwasm-action#1]
I think the dependency direction is reversed. SwiftWasm image shouldn't include carton, and carton docker image should inherit swiftwasm image.

What do you think, @MaxDesiatov ?

**Comment by MaxDesiatov** [comment]
Strictly speaking, there is no SwiftWasm image yet. 🙂 `swiftwasm/swiftwasm-action` derives from `swiftwasm/carton` as I think that significant chunk of our users would rely on `carton` anyway. And it would be more hassle to maintain a separate `swiftwasm/carton-action` image.

How's about creating a separate `swiftwasm/swift` image containing only the toolchain/SDK, which the `swiftwasm/carton` image could inherit to get access to it? We'd probably need to teach `carton` to check if `/usr/bin/swift` is a usable SwiftWasm toolchain. It currently assumes that all toolchains are installed with `swiftenv` or located in `~/.carton/sdk`.

**Comment by kateinoigakukun** [comment]
Ok, I'll create a Dockerfile repo for `swiftwasm/swift` image 👍
