### ISSUE TITLE
Allow specifying SwiftWasm version as an input

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/swiftwasm-action#3]
This would allow creating multiple jobs with matrices. Currently GHA versions can't be specified via matrix substitutions, which is apparently a limitation of GHA.

When implementing this we need to make sure that appropriate versions of `carton` images are used for the specified version input.

**Comment by Kyle-Ye** [comment]
+1 for this. See https://github.com/OpenSwiftUIProject/OpenCombine/pull/19/commits/337f1a3147bfd5c7b7ab63581055adfa691227aa

I saw WASM 5.8 and 5.9 is released recently. And I'd like to use matrices to test multi Swift version.

I guess for now I have to continue to manually use multi jobs to workaround.

**Comment by kateinoigakukun** [comment]
Maintaining this docker-based github action is a little tricky, so I'd like to deprecate this action and navigate to use https://github.com/swiftwasm/setup-swiftwasm once we support SwiftPM build plugin in carton.

So I don't have any plan to support version specifier in this action. It's already supported in setup-swiftwasm.
